### ISSUE TITLE
drp-lib/server/sv_sqlother.lua

### ISSUE THREAD

**Issue by CodeMeZone** [DarkloaderTM/mdt#3]
Do you have this lua fille? 

I'm going to make a big PR soon with tons of fixes and works with **ESX** and **QB** via the config file, I just need `sv_sqlother.lua` to see what it's calling some of the veh data.

**Comment by musicbyhawkx** [comment]
I have that file do you have discord or something?

**Comment by musicbyhawkx** [comment]
> Do you have this lua fille?
> 
> I'm going to make a big PR soon with tons of fixes and works with **ESX** and **QB** via the config file, I just need `sv_sqlother.lua` to see what it's calling some of the veh data.

here is https://anonfiles.com/FbcbZ7z2v4/sv_sqlother_lua

**Comment by musicbyhawkx** [comment]
If you have ready the MDT with QBCORE support you gonna share it?
