### ISSUE TITLE
DMV Error

### ISSUE THREAD

**Issue by LightningWolf21** [DarkloaderTM/mdt#4]
Hey. Can anyone help me with this? I get this error everytime I try to open the DMV section.

[       script:rs-mdt] SCRIPT ERROR: @rs-mdt/sv_main.lua:132: bad argument #1 to 'for iterator' (table expected, got nil)
[       script:rs-mdt] > getVehicles (@rs-mdt/sv_main.lua:132)
[       script:rs-mdt] > handler (@rs-mdt/sv_main.lua:58)
[       script:rs-mdt] > <unknown> (@mysql-async/mysql-async.js:15543)
[  script:mysql-async] [MySQL] [ERROR] [rs-mdt] An error happens for query "SELECT * FROM owned_vehicles aa LEFT JOIN vehicle_mdt a ON a.license_plate = aa.plate LEFT JOIN ____mdw_bolos at ON a.license_plate = aa.plate WHERE LOWER(plate) LIKE ? ORDER BY plate ASC : ["%wxl%"]": ER_NON_UNIQ_ERROR: Column 'plate' in where clause is ambiguous
[       script:rs-mdt] SCRIPT ERROR: @rs-mdt/sv_main.lua:249: bad argument #1 to 'for iterator' (table expected, got nil)
[       script:rs-mdt] > handler (@rs-mdt/sv_main.lua:249)
[       script:rs-mdt] > <unknown> (@mysql-async/mysql-async.js:15543)

**Comment by StuxxyOfficial** [comment]
you're not using this MDT. clearly it states RS-mdt in your error. this is has nothing to do with rs-mdt. make sure you delete whatever folder you have this mdt in and redownloaded from this github.

**Comment by cowardtv** [comment]
did you put sql?

**Comment by LightningWolf21** [comment]
> did you put sql?

Yes. I installed it the right way everything works except the DMV. I am also running esx legacy 1.2.

**Comment by LightningWolf21** [comment]
Fixed BTW Just needed to install the sql again
